#==============================
# General site config
#==============================

name: "Daniel T. Eden, Designer"
description: Designer
url: http://daneden.me

markdown: kramdown

color:
  - "#4fb5c6" # Spring
  - "#fcb500" # Summer
  - "#c64f51" # Fall
  - "#a881a2" # Winter

highlighter: true

permalink: pretty


#==============================
# File inclusions/exclusions
#==============================

include: [".htaccess"]
exclude: ["node_modules", "gulpfile.js", "Gemfile", "Gemfile.lock", "commit-hook.sh"]


#==============================
# Plugins
#==============================

assets:
  digest: true
  cache: false
  sources:
    - "_assets/css"
    - "_assets/js"
    - "uploads"
