name: "Daniel T. Eden, Designer"
description: Designer
url: http://daneden.me

gems:
- autoprefixer-rails
- coffee-script
- jekyll-assets
- jekyll-sitemap

markdown: kramdown

color: "#CA4A4C"

highlighter: true

permalink: pretty

include: [".htaccess"]
exclude: ["vendor", "node_modules", "package.json", "Gruntfile.js"]

assets:
  js_compressor: uglifier
  css_compressor: sass
  cache: true
  sources:
    - _assets/scss
    - _assets/js
  cachebust: hard
