name: Merge Dependabot PRs

on:
  pull_request:

jobs:
  merge-me:
    name: Merge Dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - name: Merge Dependabot PRs
        uses: daneden/enable-automerge-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
